# Generated by Django 2.2.5 on 2019-09-21 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('repository', models.FileField(blank=True, null=True, upload_to='')),
                ('status', models.CharField(choices=[('DRAFTED', 'DRAFTED'), ('DELEGATED', 'DELEGATED'), ('COMPLETED', 'COMPLETED')], default='DRAFTED', max_length=20)),
                ('task_point', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('type', models.CharField(choices=[('GLC', 'GLC'), ('MNC', 'MNC'), ('GOVERNMENT', 'GOVERNMENT'), ('NGO', 'NGO')], default='GLC', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=120)),
                ('is_negative', models.BooleanField(default=False)),
                ('is_positive', models.BooleanField(default=False)),
                ('is_neutral', models.BooleanField(default=False)),
                ('doer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Doer')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_tasks', to='repository.Project')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='repository.Vendor'),
        ),
    ]
