# Generated by Django 2.2.5 on 2019-09-22 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Cities',
                'ordering': ['-modified_date'],
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'States',
                'ordering': ['-modified_date'],
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nric_no', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=120)),
                ('password', models.CharField(max_length=1000)),
                ('registration', models.CharField(choices=[('STAFF', 'STAFF'), ('DOER', 'DOER')], default='REGISTERED', max_length=20)),
                ('address1', models.CharField(max_length=120, null=True)),
                ('address2', models.CharField(max_length=120, null=True)),
                ('address3', models.CharField(blank=True, max_length=120, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], max_length=20, null=True)),
                ('race', models.CharField(choices=[('MALAY', 'MALAY'), ('CHINESE', 'CHINESE'), ('INDIAN', 'INDIAN'), ('OTHERS', 'OTHERS')], max_length=60, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='signup.City')),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='signup.State')),
            ],
            options={
                'verbose_name_plural': 'Registrations',
                'ordering': ['-modified_date'],
            },
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='signup.State'),
        ),
    ]
