# Generated by Django 2.2.5 on 2019-09-22 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='registration',
        ),
        migrations.AlterField(
            model_name='registration',
            name='city',
            field=models.ForeignKey(choices=[('SHAH ALAM', 'SHAH ALAM'), ('IPOH', 'IPOH'), ('KUANTAN', 'KUANTAN')], null=True, on_delete=django.db.models.deletion.SET_NULL, to='signup.City'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='state',
            field=models.ForeignKey(choices=[('SELANGOR', 'SELANGOR'), ('PERAK', 'PERAK'), ('PAHANG', 'PAHANG')], null=True, on_delete=django.db.models.deletion.SET_NULL, to='signup.State'),
        ),
    ]
