# Generated by Django 2.2.5 on 2019-09-22 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address1',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='address2',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='address3',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateField(default='DEFAULT_VALUE'),
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='signup.City'),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='race',
            field=models.CharField(choices=[('MALAY', 'MALAY'), ('CHINESE', 'CHINESE'), ('INDIAN', 'INDIAN'), ('OTHERS', 'OTHERS')], max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='registration',
            field=models.CharField(choices=[('STAFF', 'STAFF'), ('DOER', 'DOER')], default='REGISTERED', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='signup.State'),
        ),
    ]
