# Generated by Django 2.2.5 on 2019-09-22 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0002_auto_20190922_0949'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Registration',
        ),
        migrations.AlterModelOptions(
            name='registration',
            options={'ordering': ['-modified_date'], 'verbose_name_plural': 'Registrations'},
        ),
    ]
